version: '3.8'
services:
  server:
    build: ./service
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  bot:
    build: ./app
    env_file:
      - .env
    depends_on:
      - server
